spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/jobpilot_secure
    username: jobpilot_user
    password: jobpilot_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  security:
    jwt:
      secret: "jkfjhksdfkjlsdfjksdfjksdkfsd65564sd5f56sd4g4sd4gh5s4g4s4s4g654sdg5sqgsd5gsq564g5sd4g54dsg4qs"
      expiration-ms: 3600000

logging:
  level:
    com.jobpilot.backend: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{requestId}] %logger{36} - %msg%n"
